name: Integration
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Run tests
        run: pipenv run pytest --cov=src -v -s --cov-fail-under=70

  release:
    name: Automatic Release
    runs-on: ubuntu-latest
    needs: run-tests
    if: ${{ contains(github.event.head_commit.message, 'terminada') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Merge develop into master
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git merge develop
          git push origin master